Add page for react-native-config component
microsoft/react-native-gallery pull request #25
Opened 2020-12-21 14:44 UTC by tritao

![ApplicationFrameHost_Eu84ikMZta](https://user-images.githubusercontent.com/602268/102788724-005cb680-439b-11eb-9cd3-56d297ee8ddd.png)

2021-01-05 00:03 UTC, chiaramooney commented on src/RNGalleryList.ts
> +
nit: Can you delete this extra new line?

2021-01-05 00:05 UTC, chiaramooney commented
PR just merged which adds a hyperlink section at the bottom of each component page with links to documentation. See the template page as an example. Could you add that section to this page as well?

2021-01-14 18:15 UTC, tritao commented
Updated.

2021-01-14 18:46 UTC, chiaramooney commented on src/examples/ConfigExamplePage.tsx
> +
Could you move this statement inside of the description prop?

2021-01-14 18:48 UTC, chiaramooney requested changes
One last layout change, otherwise looks great!

2021-01-15 15:05 UTC, tritao commented
Updated.

2021-01-15 23:14 UTC, chiaramooney approved these changes
👍

2021-01-15 23:15 UTC, merged